apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-team-blue
placementBindingDefaults:
  name: binding-policy-generator-team-blue
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  standards:
    - NIST SP 800-53
  namespace: blue-policies
policies:
- name: policy-nginx-install-prod
  manifests:
    - path: input-nginx/prod/
  remediationAction: enforce
  complianceType: musthave
  severity: critical
  policySets: 
    - openshift-clusters-blue-prod
- name: policy-nginx-install-nonprod
  manifests:
    - path: input-nginx/nonprod/
  remediationAction: enforce
  complianceType: musthave
  severity: critical
  policySets: 
    - openshift-clusters-blue-nonprod
policySets:
  - name: openshift-clusters-blue-prod
    description: Policies to configure team blue production openshift clusters.
    placement:
      placementPath: input/placement-prod.yaml
  - name: openshift-clusters-blue-nonprod
    description: Policies to configure team blue non-production openshift clusters.
    placement:
      placementPath: input/placement-nonprod.yaml
