apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-red-standalone-clusters-dev
  namespace: red-gitops
spec:
  clusterSets:
    - red-cluster-set
  predicates:
    - requiredClusterSelector:
            #        labelSelector:
            #          matchLabels:
            #            env: dev
        claimSelector:
          matchExpressions:
            - {key: platform.open-cluster-management.io, operator: In, values: ["AWS"]}
            - {key: controlplanetopology.openshift.io, operator: In, values: ["External"]}
