apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-nginx
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: placement-red-standalone-clusters
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'sample-nginx-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jwilms1971/acm-teams.git'
        targetRevision: main
        path: team-red/input-nginx
      destination:
        namespace: sample-nginx
        server: '{{server}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true
